# Generated by Django 6.0.4 on 2026-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Estoque Mínimo'),
        ),
    ]
