# Generated by Django 6.0.4 on 2026-08-24 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilvendedor'),
        ('estoque', '0002_alter_estoque_estoque_minimo'),
        ('produtos', '0003_precoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MontagemKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Separação'), ('separado', 'Separado')], default='pendente', max_length=20, verbose_name='Status')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token')),
                ('montado_em', models.DateTimeField(auto_now_add=True, verbose_name='Montado em')),
                ('separado_em', models.DateTimeField(blank=True, null=True, verbose_name='Separado em')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montagens_kit', to='core.local', verbose_name='Local')),
                ('montado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits_montados', to=settings.AUTH_USER_MODEL, verbose_name='Montado por')),
                ('produto_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montagens_kit', to='produtos.produto', verbose_name='Kit')),
                ('separado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_separados', to=settings.AUTH_USER_MODEL, verbose_name='Separado por')),
            ],
            options={
                'verbose_name': 'Montagem de Kit',
                'verbose_name_plural': 'Montagens de Kit',
                'ordering': ['-montado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteMontagemKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade a Debitar')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('montagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='estoque.montagemkit')),
            ],
            options={
                'verbose_name': 'Componente da Montagem',
                'verbose_name_plural': 'Componentes da Montagem',
            },
        ),
    ]
