# Generated by Django 6.0.4 on 2026-08-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_montagemkit_componentemontagemkit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montagemkit',
            name='local',
        ),
        migrations.RemoveField(
            model_name='montagemkit',
            name='montado_por',
        ),
        migrations.RemoveField(
            model_name='montagemkit',
            name='produto_kit',
        ),
        migrations.RemoveField(
            model_name='montagemkit',
            name='separado_por',
        ),
        migrations.DeleteModel(
            name='ComponenteMontagemKit',
        ),
        migrations.DeleteModel(
            name='MontagemKit',
        ),
    ]
