# Generated by Django 6.0.4 on 2026-04-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Registro de Corte',
                'verbose_name_plural': 'Registros de Corte',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCorteSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Montagem'), ('montado', 'Montado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto Cortado')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='producao_corte.registrocorte')),
            ],
            options={
                'verbose_name': 'Produto Cortado',
                'verbose_name_plural': 'Produtos Cortados',
            },
        ),
        migrations.CreateModel(
            name='ItemCorteEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Chapa/Material')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='producao_corte.registrocorte')),
            ],
            options={
                'verbose_name': 'Material Utilizado',
                'verbose_name_plural': 'Materiais Utilizados',
            },
        ),
    ]
