# Generated by Django 6.0.4 on 2026-04-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_corte', '0001_initial'),
        ('produtos', '0002_remove_produto_altura_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcortesaida',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemcortesaida',
            name='registro',
        ),
        migrations.CreateModel(
            name='ItemCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_chapa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('chapa', models.ForeignKey(limit_choices_to={'categoria__in': ['chapa', 'insumo']}, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Chapa / Material')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao_corte.registrocorte')),
            ],
            options={
                'verbose_name': 'Item de Corte',
                'verbose_name_plural': 'Itens de Corte',
            },
        ),
        migrations.CreateModel(
            name='ProdutoCortado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Montagem'), ('montado', 'Montado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('item_corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_cortados', to='producao_corte.itemcorte')),
                ('produto', models.ForeignKey(limit_choices_to={'categoria': 'produto_final'}, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto Cortado')),
            ],
            options={
                'verbose_name': 'Produto Cortado',
                'verbose_name_plural': 'Produtos Cortados',
            },
        ),
        migrations.DeleteModel(
            name='ItemCorteEntrada',
        ),
        migrations.DeleteModel(
            name='ItemCorteSaida',
        ),
    ]
