# Generated by Django 6.0.4 on 2026-06-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_corte', '0002_remove_itemcortesaida_produto_and_more'),
        ('vendas', '0006_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocorte',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_corte', to='vendas.pedido', verbose_name='Pedido'),
        ),
    ]
