# Generated by Django 6.0.4 on 2026-06-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_corte', '0003_registrocorte_pedido'),
        ('vendas', '0007_alter_pedido_percentual_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocortado',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_cortados', to='vendas.pedido'),
        ),
    ]
