# Generated by Django 6.0.4 on 2026-07-16 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_corte', '0004_produtocortado_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocortado',
            name='cortada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_cortadas', to=settings.AUTH_USER_MODEL, verbose_name='Cortada por'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='montada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Montada em'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='montada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_montadas', to=settings.AUTH_USER_MODEL, verbose_name='Montada por'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='separada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Separada em'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='separada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_separadas', to=settings.AUTH_USER_MODEL, verbose_name='Separada por'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='produtocortado',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Montagem'), ('montado', 'Montado'), ('separado', 'Separado'), ('enviado', 'Enviado')], default='aguardando', max_length=20, verbose_name='Status'),
        ),
    ]
