# Generated by Django 6.0.4 on 2026-07-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_corte', '0005_produtocortado_cortada_por_produtocortado_montada_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocortado',
            name='token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token'),
        ),
    ]
