# Generated by Django 6.0.4 on 2026-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_corte', '0006_alter_produtocortado_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtocortado',
            options={'verbose_name': 'Peça Cortada', 'verbose_name_plural': 'Peças Cortadas'},
        ),
        migrations.RemoveField(
            model_name='produtocortado',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='produtocortado',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token'),
        ),
    ]
