# Generated by Django 6.0.4 on 2026-08-25 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao_corte', '0007_alter_produtocortado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocortado',
            name='desmembrada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desmembrada em'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='desmembrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_desmembradas', to=settings.AUTH_USER_MODEL, verbose_name='Desmembrada por'),
        ),
        migrations.AddField(
            model_name='produtocortado',
            name='origem_desmembramento',
            field=models.ForeignKey(blank=True, help_text='Se esta peça nasceu de um desmembramento, aponta pro Kit original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_geradas', to='producao_corte.produtocortado', verbose_name='Origem do desmembramento'),
        ),
        migrations.AlterField(
            model_name='produtocortado',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Montagem'), ('montado', 'Montado'), ('separado', 'Separado'), ('enviado', 'Enviado'), ('desmembrado', 'Desmembrado')], default='aguardando', max_length=20, verbose_name='Status'),
        ),
    ]
