# Generated by Django 6.0.4 on 2026-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('last', models.PositiveIntegerField(default=0, verbose_name='Último valor')),
            ],
            options={
                'verbose_name': 'Sequência',
                'verbose_name_plural': 'Sequências',
            },
        ),
    ]
