# Generated by Django 6.0.4 on 2026-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(blank=True, help_text='Opcional, mas não pode repetir quando preenchido', max_length=18, verbose_name='CPF / CNPJ'),
        ),
    ]
