# Generated by Django 6.0.4 on 2026-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fornecedor_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
