# Generated by Django 6.0.4 on 2026-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fornecedor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Tag')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag de Fornecedor',
                'verbose_name_plural': 'Tags de Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(blank=True, max_length=18, verbose_name='CPF / CNPJ'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fornecedores', to='core.tagfornecedor', verbose_name='Tags'),
        ),
    ]
