# Generated by Django 6.0.4 on 2026-06-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('pagamento_pendente', 'Pagamento Pendente'), ('pedido_aberto', 'Pedido em Aberto'), ('aguard_producao', 'Aguardando Corte'), ('aguard_montagem', 'Aguardando Montagem'), ('pedido_cancelado', 'Pedido Cancelado'), ('cobranca_30_dias', 'Cobrança 30 Dias'), ('picking', 'Em Separação')], max_length=30),
        ),
    ]
