# Generated by Django 6.0.4 on 2026-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilvendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvendedor',
            name='vende_paraiso',
            field=models.BooleanField(default=False, help_text='Se ativo, este vendedor também vê a opção de gerar PDF com o timbre da Paraíso do Acrílico.', verbose_name='Vende Paraíso do Acrílico'),
        ),
    ]
