# Generated by Django 6.0.4 on 2026-04-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('insumo', 'Insumo'), ('chapa', 'Chapa de Acrílico'), ('produto_final', 'Produto Final')], max_length=20, verbose_name='Categoria')),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('m', 'Metro'), ('m2', 'Metro Quadrado'), ('cm', 'Centímetro'), ('l', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('chp', 'Chapa'), ('rolo', 'Rolo'), ('tubo', 'Tubo')], default='un', max_length=5, verbose_name='Unidade de Medida')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque Mínimo')),
                ('cor', models.CharField(blank=True, choices=[('cristal', 'Cristal'), ('branco', 'Branco'), ('preto', 'Preto'), ('azul_bebe', 'Azul Bebê'), ('rosa_bebe', 'Rosa Bebê'), ('espelhado', 'Espelhado'), ('dourado', 'Dourado'), ('outro', 'Outro')], max_length=20, verbose_name='Cor')),
                ('espessura_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Espessura (mm)')),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura (cm)')),
                ('largura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largura (cm)')),
                ('comprimento_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Comprimento (cm)')),
                ('diametro_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Diâmetro (cm)')),
                ('profundidade_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profundidade (cm)')),
                ('curvatura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Curvatura (cm)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('permite_personalizacao', models.BooleanField(default=False, help_text='Se ativo, as quantidades podem ser ajustadas por ordem de produção', verbose_name='Permite Personalização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='produtos.produto', verbose_name='Produto Final')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.fichatecnica', verbose_name='Ficha Técnica')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_fichas', to='produtos.produto', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'verbose_name_plural': 'Itens da Ficha Técnica',
                'unique_together': {('ficha', 'material')},
            },
        ),
    ]
