# Generated by Django 6.0.4 on 2026-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, choices=[('cristal', 'Cristal'), ('branco', 'Branco'), ('preto', 'Preto'), ('vermelho', 'Vermelho'), ('azul_bebe', 'Azul Bebê'), ('amarelo', 'Amarelo'), ('rosa_bebe', 'Rosa Bebê'), ('espelhado', 'Espelhado'), ('outro', 'Outro (especificar cor nas observações)')], max_length=20, verbose_name='Cor'),
        ),
    ]
