# Generated by Django 6.0.4 on 2026-04-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='altura_cm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='comprimento_cm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='comprimento_mm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='curvatura_cm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='diametro_cm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='espessura_mm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='largura_cm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='largura_mm',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='profundidade_cm',
        ),
    ]
