# Generated by Django 6.0.4 on 2026-04-20 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('movimentacoes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da Ordem')),
                ('status', models.CharField(choices=[('em_transito', 'Em Trânsito'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='em_transito', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_entrada', to='core.local', verbose_name='Local de Destino')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_saida', to='core.local', verbose_name='Local de Origem')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Ordem de Transferência',
                'verbose_name_plural': 'Ordens de Transferência',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='movimentacoes.ordemtransferencia', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Item da Ordem',
                'verbose_name_plural': 'Itens da Ordem',
            },
        ),
    ]
