# Generated by Django 6.0.4 on 2026-04-28 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('movimentacoes', '0002_ordemtransferencia_itemordemtransferencia'),
        ('produtos', '0002_remove_produto_altura_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da Ordem')),
                ('motivo', models.CharField(choices=[('venda', 'Venda'), ('perda', 'Perda / Avaria'), ('uso_interno', 'Uso Interno'), ('troca', 'Troca'), ('reposicao', 'Reposição'), ('publicidade', 'Publicidade'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], default='venda', max_length=20, verbose_name='Motivo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_saida_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_saida_lote', to='core.local', verbose_name='Local de Origem')),
            ],
            options={
                'verbose_name': 'Ordem de Saída',
                'verbose_name_plural': 'Ordens de Saída',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='movimentacoes.ordemsaida', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Saída',
                'verbose_name_plural': 'Itens da Ordem de Saída',
            },
        ),
    ]
