# Generated by Django 6.0.4 on 2026-04-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_ordemsaida_itemordemsaida'),
        ('producao_corte', '0002_remove_itemcortesaida_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='registro_corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='producao_corte.registrocorte', verbose_name='Registro de Corte'),
        ),
    ]
