# Generated by Django 6.0.4 on 2026-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_movimentacao_registro_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='motivo',
            field=models.CharField(blank=True, choices=[('compra', 'Compra'), ('venda', 'Venda'), ('perda', 'Perda / Avaria'), ('uso_interno', 'Uso Interno'), ('producao', 'Produção'), ('troca', 'Troca'), ('publicidade', 'Publicidade'), ('reposicao', 'Reposição'), ('manutencao', 'Manutenção'), ('transferencia', 'Transferência'), ('ajuste', 'Ajuste'), ('outro', 'Outro')], max_length=20, verbose_name='Motivo'),
        ),
    ]
