# Generated by Django 6.0.4 on 2026-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0006_ordemtransferencia_token_confirmacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemtransferencia',
            name='token_confirmacao',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de Confirmação'),
        ),
    ]
