# Generated by Django 6.0.4 on 2026-06-15 14:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0003_precoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, max_length=10, unique=True, verbose_name='Número do Pedido')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('in_production', 'Em Produção'), ('picking', 'Em Separação'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('tipo_venda', models.CharField(blank=True, choices=[('direct', 'Venda direta'), ('replacement', 'Reposição'), ('exchange', 'Troca'), ('maintenance', 'Manutenção'), ('advertising', 'Publicidade')], max_length=20, verbose_name='Tipo de Venda')),
                ('pedido_cliente', models.CharField(blank=True, max_length=100, verbose_name='Pedido do Cliente')),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Condição de Pagamento')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('transportadora', models.CharField(blank=True, max_length=50, verbose_name='Transportadora')),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete')),
                ('percentual_entrada', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Percentual mínimo para liberar produção', max_digits=5, verbose_name='Entrada (%)')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('total_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Produtos')),
                ('total_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Desconto')),
                ('total_impostos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Impostos')),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Geral')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='produtos.produto', verbose_name='Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero'], name='vendas_pedi_numero_111153_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='vendas_pedi_status_406326_idx'),
        ),
    ]
