# Generated by Django 6.0.4 on 2026-06-15 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('debit', 'Cartão de Débito'), ('credit', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('cash', 'Dinheiro'), ('transfer', 'Transferência')], max_length=20, verbose_name='Forma de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago')),
                ('transacao', models.CharField(blank=True, help_text='Código PIX, NSU do cartão, número do boleto etc.', max_length=100, null=True, unique=True, verbose_name='Número de Transação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pago_em', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-pago_em'],
            },
        ),
    ]
