# Generated by Django 6.0.4 on 2026-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_venda',
            field=models.CharField(blank=True, choices=[('direct', 'Venda direta'), ('replacement', 'Reposição'), ('exchange', 'Troca'), ('maintenance', 'Manutenção'), ('advertising', 'Publicidade'), ('comodato', 'Comodato')], max_length=20, verbose_name='Tipo de Venda'),
        ),
    ]
