# Generated by Django 6.0.4 on 2026-06-17 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0003_precoproduto'),
        ('vendas', '0004_alter_pedido_tipo_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_venda', models.CharField(choices=[('direct', 'Venda direta'), ('replacement', 'Reposição'), ('exchange', 'Troca'), ('maintenance', 'Manutenção'), ('advertising', 'Publicidade'), ('comodato', 'Comodato')], max_length=20)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('transportadora', models.CharField(blank=True, max_length=100)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentual_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Em elaboração'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], default='draft', max_length=20)),
                ('validade', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_origem', to='vendas.pedido')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.orcamento')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
            },
        ),
    ]
