# Generated by Django 6.0.4 on 2026-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_orcamento_itemorcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('open', 'Em aberto'), ('aguard_pagamento', 'Aguardando Pagamento'), ('aguard_producao', 'Aguardando Produção'), ('cutting', 'Em Corte'), ('assembling', 'Em Montagem'), ('picking', 'Em Separação'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], db_index=True, default='open', max_length=20, verbose_name='Status'),
        ),
    ]
