# Generated by Django 6.0.4 on 2026-06-23 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_alter_pedido_percentual_entrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('open', 'Em aberto'), ('aguard_producao', 'Aguardando Produção'), ('cutting', 'Em Corte'), ('assembling', 'Em Montagem'), ('picking', 'Em Separação'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], db_index=True, default='open', max_length=20, verbose_name='Status'),
        ),
    ]
