# Generated by Django 6.0.4 on 2026-06-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notificacao_tipo'),
        ('vendas', '0008_pedido_cancelado_em_pedido_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='local_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_saida', to='core.local', verbose_name='Local de Saída'),
        ),
    ]
