# Generated by Django 6.0.4 on 2026-06-25 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_pedido_local_saida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='operador_corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_corte', to=settings.AUTH_USER_MODEL, verbose_name='Operador de Corte'),
        ),
    ]
