# Generated by Django 6.0.4 on 2026-06-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_pedido_operador_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_expedicao',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token de Expedição'),
        ),
    ]
