# Generated by Django 6.0.4 on 2026-06-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_pedido_token_expedicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_expedicao',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de Expedição'),
        ),
    ]
