# Generated by Django 6.0.4 on 2026-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_alter_pedido_token_expedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='separado',
            field=models.BooleanField(default=False, verbose_name='Separado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='token_separacao',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token de Separação'),
        ),
    ]
