# Generated by Django 6.0.4 on 2026-07-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_pedido_separado_pedido_token_separacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Unidade')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token')),
                ('separada', models.BooleanField(default=False, verbose_name='Separada')),
                ('separada_em', models.DateTimeField(blank=True, null=True, verbose_name='Separada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='vendas.itempedido', verbose_name='Item do Pedido')),
                ('separada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_separadas', to=settings.AUTH_USER_MODEL, verbose_name='Separada por')),
            ],
            options={
                'verbose_name': 'Unidade do Pedido',
                'verbose_name_plural': 'Unidades do Pedido',
                'ordering': ['item', 'numero'],
                'unique_together': {('item', 'numero')},
            },
        ),
    ]
