# Generated by Django 6.0.4 on 2026-07-10 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_unidadepedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadepedido',
            name='montada',
            field=models.BooleanField(default=False, verbose_name='Montada'),
        ),
        migrations.AddField(
            model_name='unidadepedido',
            name='montada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Montada em'),
        ),
        migrations.AddField(
            model_name='unidadepedido',
            name='montada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_montadas', to=settings.AUTH_USER_MODEL, verbose_name='Montada por'),
        ),
    ]
