# Generated by Django 6.0.4 on 2026-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_unidadepedido_montada_unidadepedido_montada_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_separacao',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de Separação'),
        ),
    ]
