# Generated by Django 6.0.4 on 2026-08-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_alter_pedido_token_separacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovantePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('drive_file_id', models.CharField(max_length=100, verbose_name='ID no Google Drive')),
                ('drive_link', models.URLField(verbose_name='Link de Visualização')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='vendas.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Comprovante de Pagamento',
                'verbose_name_plural': 'Comprovantes de Pagamento',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
