# Generated by Django 6.0.4 on 2026-08-18 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_comprovantepagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comprovantes_envio/%Y/%m/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome Original do Arquivo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Anexado em')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Anexado por')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_envio', to='vendas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Comprovante de Envio/Retirada',
                'verbose_name_plural': 'Comprovantes de Envio/Retirada',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.DeleteModel(
            name='ComprovantePagamento',
        ),
    ]
