# Generated by Django 6.0.4 on 2026-08-18 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0018_comprovanteenvio_delete_comprovantepagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='devolvido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Devolvido em'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_devolucao',
            field=models.TextField(blank=True, verbose_name='Motivo da Devolução'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='registrado_devolucao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_devolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Devolução registrada por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('open', 'Em aberto'), ('aguard_producao', 'Aguardando Produção'), ('cutting', 'Em Corte'), ('assembling', 'Em Montagem'), ('picking', 'Em Separação'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado'), ('devolvido', 'Devolução')], db_index=True, default='open', max_length=20, verbose_name='Status'),
        ),
    ]
