# Generated by Django 6.0.4 on 2026-08-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0019_pedido_devolvido_em_pedido_motivo_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
    ]
