# Generated by Django 6.0.4 on 2026-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0020_pedido_urgente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='percentual_entrada',
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_confeccao',
            field=models.CharField(blank=True, choices=[('15', '15 dias'), ('20', '20 dias'), ('25', '25 dias'), ('30', '30 dias')], max_length=2, verbose_name='Prazo de Confecção'),
        ),
    ]
