# Generated by Django 6.0.4 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0021_remove_pedido_percentual_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovanteenvio',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreio'),
        ),
        migrations.AddField(
            model_name='comprovanteenvio',
            name='transportadora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transportadora'),
        ),
    ]
