# Generated by Django 6.0.4 on 2026-08-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0022_comprovanteenvio_codigo_rastreio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='prazo_confeccao',
            field=models.CharField(blank=True, choices=[('15', '15 dias'), ('20', '20 dias'), ('25', '25 dias'), ('30', '30 dias'), ('pronta', 'À Pronta Entrega')], max_length=10, verbose_name='Prazo de Confecção'),
        ),
    ]
