# Generated by Django 6.0.4 on 2026-08-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0023_alter_pedido_prazo_confeccao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='percentual_entrada',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='prazo_confeccao',
            field=models.CharField(blank=True, choices=[('15', '15 dias'), ('20', '20 dias'), ('25', '25 dias'), ('30', '30 dias'), ('pronta', 'À Pronta Entrega')], max_length=10, verbose_name='Prazo de Confecção'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
    ]
