# Generated by Django 6.0.4 on 2026-09-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0024_remove_orcamento_percentual_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='retirado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ficha retirada em'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='retirado_por',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ficha retirada por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prazo_confeccao',
            field=models.CharField(blank=True, choices=[('15', '15 dias úteis'), ('20', '20 dias úteis'), ('25', '25 dias úteis'), ('30', '30 dias úteis'), ('pronta', 'À Pronta Entrega')], max_length=10, verbose_name='Prazo de Confecção'),
        ),
    ]
