# Generated by Django 6.0.4 on 2026-09-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0025_pedido_retirado_em_pedido_retirado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressaoFichaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresso_em', models.DateTimeField(auto_now_add=True, verbose_name='Impresso em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressoes_ficha', to='vendas.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Impresso por')),
            ],
            options={
                'verbose_name': 'Impressão de Ficha de Envio',
                'verbose_name_plural': 'Impressões de Ficha de Envio',
                'ordering': ['-impresso_em'],
            },
        ),
    ]
