# Generated by Django 6.0.4 on 2026-08-10 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_notificacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('energia', 'Energia elétrica'), ('agua', 'Água'), ('telefonia', 'Telefonia/Internet'), ('materia_prima', 'Matéria-prima'), ('aluguel', 'Aluguel'), ('impostos', 'Impostos'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('competencia', models.DateField(help_text='Mês de referência da despesa (ex: 01/07/2026 para a conta de julho)')),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar_criadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagarParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('parcial', 'Pago parcialmente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='aberto', max_length=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contapagar')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('cheque', 'Cheque')], max_length=20)),
                ('transacao', models.CharField(blank=True, max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.contapagarparcela')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddIndex(
            model_name='contapagarparcela',
            index=models.Index(fields=['status', 'vencimento'], name='financeiro__status_17e3fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contapagarparcela',
            unique_together={('conta', 'numero')},
        ),
    ]
