# Generated by Django 6.0.4 on 2026-08-11 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='juros_multa',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Valor extra cobrado por atraso (já incluso na conta/boleto), não abate saldo devedor.', max_digits=12),
        ),
    ]
