# Generated by Django 6.0.4 on 2026-08-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_pagamentocontapagar_juros_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagarparcela',
            name='status',
            field=models.CharField(choices=[('aberto', 'A vencer'), ('parcial', 'Pago parcialmente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='aberto', max_length=10),
        ),
    ]
