# Generated by Django 6.0.4 on 2026-06-08 20:01

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(editable=False, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('documento', models.CharField(blank=True, max_length=30, verbose_name='CPF / CNPJ / Documento')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Municipal')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('contato', models.CharField(blank=True, max_length=255, verbose_name='Pessoa de Contato')),
                ('pais', django_countries.fields.CountryField(default='BR', max_length=2, verbose_name='País')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='Logradouro / Street')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número / Number')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento / Suite')),
                ('bairro', models.CharField(blank=True, max_length=255, verbose_name='Bairro / District')),
                ('cidade', models.CharField(blank=True, max_length=255, verbose_name='Cidade / City')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código Postal / ZIP')),
                ('regiao', models.CharField(blank=True, max_length=100, verbose_name='Estado / Province / Region')),
                ('ativo', models.BooleanField(default=True)),
                ('is_fornecedor', models.BooleanField(default=False, verbose_name='É fornecedor?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
