# Generated by Django 6.0.4 on 2026-06-18 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_precoproduto'),
        ('vendas', '0006_alter_pedido_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMontagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_montagem', to='vendas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Registro de Montagem',
                'verbose_name_plural': 'Registros de Montagem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemMontagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='montagem.registromontagem')),
            ],
            options={
                'verbose_name': 'Item de Montagem',
                'verbose_name_plural': 'Itens de Montagem',
            },
        ),
    ]
